"""initial schema

Revision ID: 499dfbedfda9
Revises:
Create Date: 2025-11-08 10:10:12.703765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "499dfbedfda9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index("ix_projects_created_at", "projects", ["created_at"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("storage_uri", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_uploads_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    op.create_index("ix_uploads_created_at", "uploads", ["created_at"], unique=False)
    op.create_index(op.f("ix_uploads_project_id"), "uploads", ["project_id"], unique=False)
    op.create_index("ix_uploads_status", "uploads", ["status"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_jobs_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_created_at", "jobs", ["created_at"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_upload_id"), "jobs", ["upload_id"], unique=False)
    op.create_table(
        "graphs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("json_blob", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_graphs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_graphs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graphs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_graphs_job_id")),
        sa.UniqueConstraint("project_id", "version", name="uq_graphs_project_version"),
    )
    op.create_index("ix_graphs_created_at", "graphs", ["created_at"], unique=False)
    op.create_index("ix_graphs_job_id", "graphs", ["job_id"], unique=False)
    op.create_index(op.f("ix_graphs_project_id"), "graphs", ["project_id"], unique=False)
    op.create_index("ix_graphs_project_version", "graphs", ["project_id", "version"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
            name=op.f("fk_findings_graph_id_graphs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index("ix_findings_code", "findings", ["code"], unique=False)
    op.create_index(op.f("ix_findings_graph_id"), "findings", ["graph_id"], unique=False)
    op.create_index(
        "ix_findings_graph_severity", "findings", ["graph_id", "severity"], unique=False
    )
    op.create_index("ix_findings_severity", "findings", ["severity"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_findings_severity", table_name="findings")
    op.drop_index("ix_findings_graph_severity", table_name="findings")
    op.drop_index(op.f("ix_findings_graph_id"), table_name="findings")
    op.drop_index("ix_findings_code", table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_graphs_project_version", table_name="graphs")
    op.drop_index(op.f("ix_graphs_project_id"), table_name="graphs")
    op.drop_index("ix_graphs_job_id", table_name="graphs")
    op.drop_index("ix_graphs_created_at", table_name="graphs")
    op.drop_table("graphs")
    op.drop_index(op.f("ix_jobs_upload_id"), table_name="jobs")
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_created_at", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_uploads_status", table_name="uploads")
    op.drop_index(op.f("ix_uploads_project_id"), table_name="uploads")
    op.drop_index("ix_uploads_created_at", table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index("ix_projects_created_at", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
