"""remove redundant index on graphs.job_id

Revision ID: c169ee48cab3
Revises: 499dfbedfda9
Create Date: 2025-11-08 10:18:38.447337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c169ee48cab3'
down_revision: Union[str, None] = '499dfbedfda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graphs_job_id'), table_name='graphs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_graphs_job_id'), 'graphs', ['job_id'], unique=False)
    # ### end Alembic commands ###
