"""add_server_defaults_for_status_and_version

Revision ID: e0e8921bcd37
Revises: 8519ba4bca56
Create Date: 2025-11-08 12:12:14.909980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e8921bcd37'
down_revision: Union[str, None] = '8519ba4bca56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add server default for uploads.status
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.String(length=50),
                              server_default='pending',
                              existing_nullable=False)
    
    # Add server default for jobs.status
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.String(length=50),
                              server_default='pending',
                              existing_nullable=False)
    
    # Add server default for graphs.version
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.alter_column('version',
                              existing_type=sa.Integer(),
                              server_default='1',
                              existing_nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove server default from graphs.version
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.alter_column('version',
                              existing_type=sa.Integer(),
                              server_default=None,
                              existing_nullable=False)
    
    # Remove server default from jobs.status
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.String(length=50),
                              server_default=None,
                              existing_nullable=False)
    
    # Remove server default from uploads.status
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.String(length=50),
                              server_default=None,
                              existing_nullable=False)
    
    # ### end Alembic commands ###
