"""add check constraint for job timestamps and server defaults for updated_at

Revision ID: 8519ba4bca56
Revises: c169ee48cab3
Create Date: 2025-11-08 10:21:07.517486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8519ba4bca56"
down_revision: str | None = "c169ee48cab3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add check constraint to jobs table
    # Note: SQLite supports CHECK constraints but doesn't enforce them until recreate
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_jobs_finished_after_started",
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
        )

    # Add server defaults for updated_at columns
    # Note: These changes primarily affect PostgreSQL behavior; SQLite has limited support
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=True,
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=True,
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove server defaults from updated_at columns
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=True,
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=True,
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=True,
        )

    # Remove check constraint from jobs table
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("ck_jobs_finished_after_started", type_="check")

    # ### end Alembic commands ###
